### ISSUE TITLE
Decoupling capacitor grounding

### ISSUE THREAD

**Issue by tuckbick** [volzotan/drawbot#2]
Hey @volzotan! I've learned so much from the blog post about your gigantic pen plotter and have built version of my own! The hardware is done, and I'm just working on the electronics now.

I have a question about the PCB schematic included in this repo [here](https://github.com/volzotan/drawbot/tree/master/ethernet_jack_cnc_shield_2.5). Upon inspection (I'm using EAGLE), I don't see that the decoupling capacitors are connected to any sort of ground. Was this intentional? Hopefully you can take 2 mins to explain your reasoning to me. Thank you in advance! 🙏

**Comment by volzotan** [comment]
Hey tuckblick, no, I was basically just lazy and did the absolute minimum to get a working controller board. Now (a few years later) I would not recommend to go with the "double microcontroller" solution but would rather use [FluidNC](https://github.com/bdring/FluidNC). In the FluidNC [wiki](https://github.com/bdring/FluidNC/wiki/Hardware-that-Runs-FluidNC) you can find an overview of off-the-shelf boards that are compatible. I am using the Fysetc E4 with integrated Trinamic TMC2209s. Sensorless homing can be activated by editing the config file and it's very little extra work while everything is still grbl compatible.
